---
- name: Create the flamestream directory
  file:
    path: "{{ flamestream_dir }}"
    state: directory
  tags: deliver

- name: Copy the worker application
  copy:
    src: flamestream-runtime-1.0-SNAPSHOT.jar
    dest: "{{ flamestream_dir }}"
  tags: deliver

- name: Copy the dependencies
  copy:
    src: lib
    dest: "{{ flamestream_dir }}"
  tags: deliver

- name: Copy the entrypoint
  copy:
    src: entrypoint.sh
    dest: "{{ flamestream_dir }}"
  tags: deliver

- name: Copy the config
  template:
    src: worker.json
    dest: "{{ flamestream_dir }}"
  tags: deliver

- name: Run flamstream
  raw: "cd {{ flamestream_dir }} && bash entrypoint.sh restart worker.json"
  tags: bootstrap
