---
- name: Clean shm
  shell: rm -rf /dev/shm/aeron*

- name: Copy the worker config
  template:
    src: worker.json.j2
    dest: "{{ flamestream_dir }}/worker.json"

- name: Run flamstream
  shell: "cd {{ flamestream_dir }} && bash entrypoint.sh restart worker.json"
