---
- name: Copy the worker config
  template:
    src: worker.json
    dest: "{{ flamestream_dir }}"

- name: Run flamstream
  raw: "cd {{ flamestream_dir }} && bash entrypoint.sh restart worker.json"
