---
- name: Clean shm
  shell: rm -rf /dev/shm/aeron*

- name: Clean data dir
  file:
    path: "{{ flamestream_dir }}/data/"
    state: absent

- name: Run flamestream
  shell: "cd {{ flamestream_dir }} && bash entrypoint.sh restart"
  environment:
    ID: "{{ inventory_hostname }}"
    LOCAL_ADDRESS: "{{ inventory_hostname }}:{{ flamestream_worker_port }}"
    SNAPSHOT_PATH: "{{ flamestream_dir }}/data"
    GUARANTEES: "{{ guarantees }}"
    ZK_STRING: "{{ groups['manager'][0] }}:{{ zookeeper_client_port }}"
