---
- name: Clean the bench directory
  file:
    path: "{{ bench_dir }}"
    state: absent
  tags:
    - clean

- name: Create the bench dir
  file:
    path: "{{ bench_dir }}"
    state: directory
  tags: deliver

- name: Copy the bench application
  copy:
    src: flamestream-benchmark-1.0-SNAPSHOT-uber.jar
    dest: "{{ bench_dir }}/bench.jar"
  tags: deliver

- name: Copy the wiki dump
  copy:
    src: wiki.xml
    dest: "{{ bench_dir }}/wiki.xml"
  tags: deliver

- name: Copy the configuraion file
  template:
    src: bench.conf.j2
    dest: "{{ bench_dir }}/bench.conf"
  tags: deliver

- name: Start the flamestream bench
  shell: >
    java -Xms713m -Xmx713m -XX:+PrintGC -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError \
    -jar {{ bench_dir }}/bench.jar {{ bench_dir }}/bench.conf \
    > {{ bench_dir }}/flamestream_bench.log 2>&1
  tags: run

- name: Fetch bench logs
  fetch:
    src: "{{ bench_dir }}/flamestream_bench.log"
    dest: flamestream_bench.log
  tags: run
