---
- name: Create zookeeper dir exists
  file:
    path: "{{ zookeeper_dir }}"
    state: directory
  tags: deliver

- name: Create tarball dir
  file:
    path: "{{ zookeeper_tarball_dir }}"
    state: directory
  tags: deliver

- name: Download ZK tarball
  get_url: 
    url: "{{ zookeeper_url }}"
    dest: "{{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  tags: deliver

- name: Unpack the tarball
  command: tar -xf {{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz --strip-components=1
  args: 
    chdir: "{{ zookeeper_dir }}" 
    creates: "{{ zookeeper_dir }}/bin"
  tags: deliver

- name: Configure the zookeeper
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_dir }}/conf/zoo.cfg"
  notify:
    - restart zk
  tags: deliver
