---
version: '3'

services:
  worker:
    command: sleep 365d
    image: debian
    networks: 
      - workers

networks:
  workers:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
