---
- name: Install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Prepare cluster
  hosts: all
  roles:
    - { role: common-packages }

- name: Setup zookeeper
  hosts: manager
  roles:
    - { role: zookeeper  }

- name: Deliver flamestream artifacts
  hosts: all
  roles:
    - { role: flamestream-common  }

- name: Setup config
  hosts: manager
  roles:
    - { role: flamestream-config }

- name: Init workers
  hosts: workers
  roles:
    - { role: flamestream-worker }

- name: Run the benchmark
  hosts: bench
  roles:
    - { role: flamestream-bench }

- name: Destroy flamestream
  hosts: workers
  roles:
    - { role: flamestream-destroy }

- name: Destroy zookeeper
  hosts: manager
  roles:
    - { role: zookeeper-destroy }

- name: Destroy bench
  hosts: bench
  roles:
    - { role: flamestream-bench-destroy }
