---
- name: Install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Prepare cluster
  hosts: all
  remote_user: root
  roles:
    - { role: common }

- name: Setup zookeeper
  hosts: manager
  remote_user: root
  roles:
    - { role: zookeeper  }

#- hosts: workers
#  become: yes
#  roles:
#    - { role: flamestream-worker }
#
#- hosts: manager
#  become: yes
#  roles:
#    - { role: flamestream-bench }
