---
- name: Install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Prepare cluster
  hosts: all
  roles:
    - { role: common-packages }

- name: Setup zookeeper
  hosts: manager
  roles:
    - { role: zookeeper  }

- name: Deliver flamestream artifacts
  hosts: all
  roles:
    - { role: flamestream-common  }

- name: Setup config
  hosts: manager
  roles:
    - { role: flamestream-config }

- name: Init workers
  hosts: workers
  roles:
    - { role: flamestream-worker }

- name: Log cpu usage
  hosts: workers
  tasks:
    - name: Start background logging
      shell: nohup vmstat -nSm 1 < /dev/null > /vmstat.log &

- name: Run the benchmark
  hosts: bench
  roles:
    - { role: flamestream-bench }

- name: Log cpu usage
  hosts: workers
  tasks:
    - name: Kill backgroung logging
      shell: pkill -n vmstat
    - name: Fetch cpustats
      fetch:
        src: /vmstat.log
        dest: vmstat.log

- name: Destroy flamestream
  hosts: workers
  roles:
    - { role: flamestream-destroy }

- hosts: workers
  tasks:
    - name: Fetch replay times
      fetch:
        src: /tmp/elements.cnt
        dest: flamestream/rates/{{ groups['workers'] | length }}/{{ rate }}/{{ inventory_hostname }}.cnt
        flat: true

- hosts: bench
  tasks:
    - name: Fetch latencies
      fetch:
        src: /tmp/lat.data
        dest: flamestream/latency/{{ groups['workers'] | length }}/{{ rate }}/lat.data
        flat: true

- name: Destroy zookeeper
  hosts: manager
  roles:
    - { role: zookeeper-destroy }

- name: Destroy bench
  hosts: bench
  roles:
    - { role: flamestream-bench-destroy }

- hosts: all
  tasks:
    - name: Fetch traces
      fetch:
        src: /tmp/trace.csv
        dest: flamestream/traces/{{ inventory_hostname }}.csv
        flat: true
