---
- name: Install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Prepare cluster
  hosts: all
  roles:
    - { role: common-packages }

- name: Setup zookeeper
  hosts: manager
  roles:
    - { role: zookeeper  }

- name: Deliver flamestream artifacts
  hosts: all
  roles:
    - { role: flamestream-common  }

- name: Setup config
  hosts: manager
  roles:
    - { role: flamestream-config }

- name: Init workers
  hosts: workers
  roles:
    - { role: flamestream-worker }

- hosts: bench
  tasks:
    - pause:

- name: Run the benchmark
  hosts: bench
  roles:
    - { role: flamestream-bench }

- name: Destroy flamestream
  hosts: workers
  roles:
    - { role: flamestream-destroy }

- name: Destroy zookeeper
  hosts: manager
  roles:
    - { role: zookeeper-destroy }

- name: Destroy bench
  hosts: bench
  roles:
    - { role: flamestream-bench-destroy }

- hosts: workers
  tasks:
    - name: Fetch replay times
      fetch:
        src: /tmp/elements.cnt
        dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flamestream/rate/{{ inventory_hostname }}.cnt
        flat: true

- hosts: bench
  tasks:
    - name: Fetch latencies
      fetch:
        src: /tmp/lat.data
        dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flamestream/latency/lat.data
        flat: true

- hosts: all
  tasks:
    - name: Fetch traces
      fetch:
        src: /tmp/trace.csv
        dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flamestream/traces/{{ inventory_hostname }}.csv
        flat: true
