---
- name: Install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Prepare cluster
  hosts: all
  roles:
    - { role: common-packages }

- name: Deliver flink
  hosts: all
  roles:
    - { role: flink-common }

- name: Run flink manager
  hosts: manager
  roles:
    - { role: flink-job-manager }

- name: Run flink worker
  hosts: workers
  roles:
    - { role: flink-task-manager }

- name: Run flink bench
  hosts: bench
  roles:
    - { role: flink-bench }

- name: Destroy flink manager
  hosts: manager
  roles:
    - { role: flink-job-manager-destroy }

- name: Destroy flink worker
  hosts: workers
  roles:
    - { role: flink-task-manager-destroy }

- hosts: bench
  tasks:
    - name: Fetch latencies
      fetch:
        src: /tmp/lat.data
        dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flink/latency/lat.data
        flat: true

- hosts: all
  tasks:
    - name: Fetch traces
      fetch:
        src: /tmp/{{ item }}.csv
        dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flink/traces/{{ item }}/{{ inventory_hostname }}.csv
        flat: true
      with_items:
        - source
        - sink
        - enforcer
        - flatmap

- hosts: bench
  tasks:
    - name: Fetch traces
      fetch:
        src: /tmp/{{ item }}.csv
        dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flink/traces/{{ item }}/{{ inventory_hostname }}.csv
        flat: true
      with_items:
        - trace
