---
- name: Install Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: Add hosts
  hosts: all
  tasks:
    - shell: "echo \"127.0.0.1 $(hostname)\" | tee -a /etc/hosts"
