---
all:
  children:
    zookeeper:
      hosts:
        worker1:
    manager:
      hosts:
        worker1:
    workers:
      hosts:
        worker1:
        worker2:
  vars:
    ansible_user: root
    ansible_connection: docker
